version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: cccrizzz/ccpd-django-service
    command: python manage.py runserver_plus 0.0.0.0:8000
    # command: gunicorn --bind :8000 --workers 3 CCPDController.wsgi:application
    ports:
      - 8000:8000